# .gitlab-ci.yml
stages:
  - test

unit_tests:
  image: node:20
  stage: test
  before_script:
    - npm install
  script:
    - echo "Running unit tests..."
    - npm run test:rep
  artifacts:
    when: always
    paths:
      - rspec.xml
    reports:
      junit: rspec.xml

e2e_tests:
  image: cypress/browsers:node16.16.0-chrome107-ff107-edge
  stage: test
  script:
    # install dependencies
    - npm ci
    # start the server in the background
    - npm run dev &
    # run Cypress tests
    - npx cypress run --browser firefox
  after_script:
    # stop the server
    - npm stop
