# .gitlab-ci.yml
stages:
  - test

unit_tests:
  image: node:20
  stage: test
  script:
    - npm ci
    - npm run test:rep
  artifacts:
    when: always
    paths:
      - rspec.xml
    reports:
      junit: rspec.xml

e2e_tests:
  image: cypress/browsers:node16.16.0-chrome107-ff107-edge
  stage: test
  script:
    - npm ci
    - npm run dev &
    - npx cypress run --browser firefox
    # - npx run cy:run
