# .gitlab-ci.yml
image: node:20

before_script:
  - npm install

unit_tests:
  stage: test
  script:
    - echo "Running unit tests..."
    - npm run test:rep
    - npm run test
  artifacts:
    when: always
    paths:
      - rspec.xml
    reports:
      junit: rspec.xml
