# .gitlab-ci.yml
image: node:18

stages:
  - test

cache:
  paths:
    - node_modules/

before_script:
  - npm install

unit_tests:
  stage: test
  script:
    - echo "Running unit tests..."
    - npm test
